server:
  port: ${port:9091}

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.itheima.domin

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

#    应用名称
  application:
    name: provider-server

# Eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

